# Generated by Django 3.0.8 on 2020-07-30 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=30)),
                ('mon', models.TextField(default='')),
                ('tue', models.TextField(default='')),
                ('wed', models.TextField(default='')),
                ('thr', models.TextField(default='')),
                ('fri', models.TextField(default='')),
                ('sat', models.TextField(default='')),
                ('sun', models.TextField(default='')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Meeting')),
            ],
        ),
    ]
